server:
  servlet:
    context-path: /api
spring:
  application:
    name: Vulpes
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    url: ${DATABASE_URL}
  flyway:
    default-schema: vulpes
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: vulpes
        format_sql: true
cors:
  allowed-origins: ${CORSALLOWEDORIGINS:http://localhost:3000}
  allowed-methods: ${CORSALLOWEDMETHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORSALLOWEDHEADERS:*}
  exposed-headers: ${CORSEXPOSEDHEADERS:Authorization}
  allow-credentials: ${CORSALLOWCREDENTIALS:true}
  max-age: ${CORSMAXAGE:3600}
jwt:
  secret: ${JWTSECRET:ed6341f986937a04de35096f970bea82c40d3c9c847fcfc327b49f8acde20722}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
