server:
  servlet:
    context-path: /api
spring:
  application:
    name: Vulpes
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DBUSERNAME:postgres}
    password: ${DBPASSWORD:postgres}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dev}
  flyway:
    default-schema: vulpes
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: vulpes
        format_sql: true
jwt:
  secret: ${JWTSECRET:ed6341f986937a04de35096f970bea82c40d3c9c847fcfc327b49f8acde20722}